MongoDBUsername = "root"
MongoDBPassword = "password"
PrivateKeyString = """
-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEAxdCOPL6YMc7PHrlXsO/GR3M4GAogB9gdfs5vKG6v8DNpQ/BV
MSlpAuXauOrSbBLoJD27nAKH5f+URu40tgEuIxdYjKwNtpjNRbE3/rJyvvIQK5SC
+PbGYvBZsmBJWQ7eSqUzQwFvxyx17kaPwnPxpj0c9terjprfF4xjMHH2vpHBKwjE
Tt2/CyE3HIgLQ3tIu0mjbUc5dAkyMAHlyrAcopvLFY7jOTVKtbALknn04qARvovE
TWx88EoYD37iE9+Xa8OGsyL2PHb1OikSu+6tqa9SAHNCyyTbDFhvoCtY+Ic/HW9Y
4n+qoEEuA07wD7vjCdl6x+hhLHDeCeh4MOVWHjPnb6M1ABohVGsgj+p4oxV34KWV
EkVEMCj3zpUBHf7J3PnW0An+KXXGI/qMnhjkap8d9LWyE72g0FVdjEZ3Q0cgC2uI
RVC1DJqqMoszLjWhTFTVkcTqGBHlWqwtXYfmytB108OCS1WYmYm1KnIIOA2EyG9r
JMqa6AIG0AwcwkZfYEPe9p7ggrGjlB9zJDuH+wA0cjaCnfhMS/Hzw2I3fk36FonT
27YA6kXTiO3U79+KEDuebo5syA1Uk2jxFsyDdxrOlUgORJIH+wmh9wYMD1w0fWsr
83ldtR7V8RXbp26AV3tDEqZYa9muixifzWl3M8TBqqQv5iC7FbjwNcCUl8sCAwEA
AQKCAgEAwBRsGTXlKPAtFCNasBeTjAuoW0dxpMxIj7o6G6OnOXFidLLotk0Eh+jT
wp1Z59FQEujSxIF8nmvW+i0Rh+2LdE2WETp8MmMbZ+HWgn2aiCkaZIbXypItPyMt
pdRzRIP4e7kAFr9NX7SfatiffW0CJ67N8i6nilh96irKod73fkKftH7Vx9LwUAlX
r1+2uDb8/8dYZqMzeaX4Ur9096ScmZT31R4jK4jA271u7zN3A5v0vvaOjbObeeQo
ittlAXEqYlzA7i8ztLC6HFiHtW7kuJDh6kgBgqpt/QXelkOhJ+qD8bwOLhlTgDrq
SBIdbtm9cvH3lCfkO7f5Etvl4Wy/eepdxnWkf5z5IVLx4lixHz88hB5266dpLUuM
KiyWVVdY2DeZH/ieaDL6KHZKMgiO+M19JbtXdlvZdAe0efbDGAkOzCs+Au4/VkGb
MrLNEWTpLXZx5gU6eANaS6irXE7VaBq0dYj2CeC13uMb8z28FZn4sFIC8PxjitJ+
5IAzKPYKWQIclCy0pXg9OhYEQ4tIbd2CGhIo5ECG+4FVr68P4YVyz1GY7AJNsh9q
KFWTfS1C8CyYjUvOFi8HUnZAbjh3HSVidQftocCUVvNdAGEOVEqaFIuMMI+YHF7C
UAwdaP1MRRmR29XIGVtQ2rj+Wss6+twJ62OiuAKCeflIvDlNMKECggEBAPzyQdVv
ikP7jXoxMBOHD2cUnwfsG8/rkupu5aodZG12jWhn213+0zT7y1dvmnoR3XejXCTc
sbUK2NNlrniSzFnwRvSyi9P1rtjDFg8H+m6+IitFt2ESg50tFeBMnNCCRO+7/oXH
++E0Kweo4SV+6xiPEMcEMjzHmWm0tTZ3CRtopxTGOesqhnO7ijgMuK34C/nwZiIA
21MPMTP4f6nMbDPkvb5DAHIE2waW23ZxuTPXhnfy03MWO4lYSj+kHtOOeuE2g4DU
M6+pCljWjspxlo+RCpvqriGHrHPQat5FuMwE3YJInBhVbkrwN3YX7dZXqX5WpMrr
pvcToI5IpRi2eFsCggEBAMgz6VNipZXgRQpCAok+vigcbuWSXLBbhybuW7ze2XlT
FliEaUIWUexJIrexARU/AlQ3grUz+gbAjYerqNW6iRnaQ/zB+tlW8acKZOhmSeHi
3plqNreYXlBFlxp2reOJQ3sVSWb8zNW1k9kN25snJov6rzYLYle9lDSnDf5MngVj
sHDHYOZxfwQZiLv6/AnNkyCjuDH9gSoVTn2H+4tElQLVjdBz3ZseuPL4qSvKnv3L
auIPTszxo/4FBoA+AYHJqDTZQ/xG7Z2JO+TzWMLGdsjCTIKFUw3B2PZFB30XDl4r
eiRllL9W+GDpIRraV4lpvJKAor6PBS9ZNkI+2mXY+VECggEAVFj8dw3wz2as8NhC
LeDV1AveVCf5xkXKAf7k+us+N/pWgUBQuHFnQL3OOuPuYVJfxatl6KznXXW2hBfe
LDrXhg5HuwVm91Fv8rxrOKvyaMdiYYen9OjVlq4YI2moyScHkeHgp//eEGTzDGTW
X0iJYPEkKRlPH1F36PXnj7f2A3vMa3MGkVLm7uTU3IfxdaHHbJsrk58xg+sG/0uY
VqjiVBOs6isxlNPlrbbUjBS0K4NtRcZlmHULeWtFpx81YFqcw0kIZQdeDO+TkbhK
eVuTV2CIZyHE202AxkXzvRcG3pGow+8ujja+xqJ//BNSri0hSg3eegRG8xFKcufq
lekTDQKCAQAAsk2JgLpavyD+XCRuHc3DjfXEzrGL24Wo2QNwsMXI6kUVocBL/o/i
Zo68XN1IGaQEbv0BbGDeTSUw56P6ul9nu56o7nPU9bx5fEvFkzWGl6d2mSv/j4Qk
e1l/OhJ4zC1z7CsJNK/xvmP5SVcOPyCfNAwQABIjhAFT/ZDK5bFXC3W9rrPjmVl7
xir3nHPsBM8SOf+WDO+6GcDgJuz1GxP5ooyPwRdwRrcWAU91W4saDu8cQjlf9SdA
5vuSzqRqsyzmoireYdDJz4Rp037njpEzOZnSimwzjA0ZLjxMbxwZr8UJA2F1GPRc
QfNfiIrta3TAfboTN6Qo+gJ6UIWp/QtBAoIBAQDgl7xVYD1N2N+r6aJCuOVMECN0
4dokmJZMf2Y1RYoFqRegmryNZLhbS8nBgWSKK9S2XKpjc5F2GCyDYXSPXaDt3oca
YAOYIimtqhBKmG/ycV79gZbiMVwpJhGhHiTVQhBdhsLn4AnfwWUzqUvKK6f8re0W
S0IsncL/QbJaTPD8po/FlQHIkjvga+pe/ci0criVNslJrMLlqx87ATkZQTrhuNYo
/o2f8M+9rqnsYCCWiMEkSf/d8yzGO5jREufauaGIpELt0wLE0YbS8Idvv77XtCES
FvQbdQqZbtK66IJurH+Eka+ILoL2wBLsDg0p276ynM20WFRfTjO/ofC+Wi1w
-----END RSA PRIVATE KEY-----"""